name: pmfrontend
description: "Pale Messenger"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  signalr_netcore: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TrajanPro
      fonts:
        - asset: assets/fonts/TrajanPro-Regular.ttf
    - family: gg_sans
      fonts:
        - asset: assets/fonts/gg_sans_regular.ttf
          weight: 400
        - asset: assets/fonts/gg_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/gg_sans_semibold.ttf
          weight: 600
        - asset: assets/fonts/gg_sans_bold.ttf
          weight: 700
          